CREATE TABLE pharmacy_orders (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    pharmacy_id BIGINT NOT NULL,
    prescription_id BIGINT,
    status ENUM('PENDING','REVIEWING','VALIDATED','PAYMENT_PENDING','PAID','AWAITING_CHOICE','ASSIGNING','ASSIGNED','RESERVED','READY_FOR_PICKUP','DELIVERY_REQUESTED','OUT_FOR_DELIVERY','PICKED_UP','DELIVERED','CANCELLED') NOT NULL DEFAULT 'PENDING',
    total_price DECIMAL(12, 2) NOT NULL,
    delivery_address VARCHAR(255) NOT NULL,
    delivery_type ENUM('PICKUP','HOME_DELIVERY'),
    scheduled_delivery_date DATE,
    pharmacist_note VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (pharmacy_id) REFERENCES pharmacies(id) ON DELETE CASCADE,
    FOREIGN KEY (prescription_id) REFERENCES prescriptions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
