spring.application.name=demosec

################ SERVER ################
server.port=8081
server.servlet.context-path=/springsecurity

################ DATABASE ################
spring.datasource.url=jdbc:mysql://localhost:3306/demospringsecurity?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

################ JPA ################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

################ JWT ################
app.jwt.secret=MySuperSecretKeyForJwtAuthSpringSecurity2026MySuperSecretKey
app.jwt.expiration-ms=3600000

logging.level.org.springframework.security=DEBUG
logging.level.com.aziz.demosec.security.jwt=DEBUG


health.thresholds.overeating-surplus=300
health.thresholds.undereating-surplus=300
health.thresholds.no-progress-weight-delta=0.1
health.thresholds.no-progress-days-window=7

#api
voicerss.api.key=6471bbf3df584cb7a0485f7d095e8c0f
voicerss.api.url=https://api.voicerss.org/
voicerss.api.language=en-us
voicerss.api.codec=MP3
voicerss.api.format=44khz_16bit_stereo

cohere.api.key=cohere_qo8RqShwbxzcQuhGr3mOxmlnHSIlnIwz6Bduq8pu1kC29E
cohere.api.url=https://api.cohere.com/v1/chat