apiVersion: v1
kind: Service
metadata:
  name: medicarepi-backend-service
spec:
  type: NodePort # Allows external access from outside the cluster node
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
  selector:
    app: medicarepi-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicarepi-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicarepi-backend
  template:
    metadata:
      labels:
        app: medicarepi-backend
    spec:
      containers:
      - name: backend
        image: azizmelki1/medicarepi-backend:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/demospringsecurity?createDatabaseIfNotExist=true&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root-password"
        - name: SERVER_PORT
          value: "8081"
