package com.aziz.demosec.Entities;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_VALIDATED,
    DELIVERY_CHOICE_REQUIRED,
    PAYMENT_CONFIRMED,
    DELIVERY_ASSIGNED,
    DELIVERY_PICKED_UP,
    OUT_FOR_DELIVERY,
    DELIVERED,
    ORDER_CANCELLED,
    ORDER_REJECTED,
    NO_DRIVER_AVAILABLE,
    REG_REQ,
    ACCOUNT_ACTIVATED,
    NEW_HOMECARE_REQUEST,
    HOMECARE_REQUEST_ACCEPTED,
    HOMECARE_IN_PROGRESS,
    HOMECARE_COMPLETED
}
